[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Chrys Lovelace <chryslovelace@gmail.com>"]
edition = "2018"

[dependencies]
scan_fmt = "0.1.3"
itertools = "0.7.11"
chrono = "0.4.6"